import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

export async function captureImageCard(elementId: string, filename: string = 'typing-result.png') {
  const element = document.getElementById(elementId);
  if (!element) return;
  
  try {
    const canvas = await html2canvas(element, {
      backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--background-color').trim() || '#0f172a',
      scale: 2, // high res
    });
    
    const image = canvas.toDataURL('image/png');
    const link = document.createElement('a');
    link.href = image;
    link.download = filename;
    link.click();
  } catch (error) {
    console.error('Error capturing image:', error);
  }
}

export async function generateCertificate(name: string, wpm: number, accuracy: number, date: string) {
  try {
    // Landscape A4 certificate
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4'
    });

    const width = doc.internal.pageSize.getWidth();
    const height = doc.internal.pageSize.getHeight();

    // Background
    doc.setFillColor(15, 23, 42); // slate-900 roughly
    doc.rect(0, 0, width, height, 'F');
    
    // Border
    doc.setDrawColor(56, 189, 248); // sky-400
    doc.setLineWidth(2);
    doc.rect(10, 10, width - 20, height - 20);
    
    // Text
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(40);
    doc.setFont("helvetica", "bold");
    doc.text("Certificate of Achievement", width / 2, 50, { align: 'center' });

    doc.setFontSize(16);
    doc.setFont("helvetica", "normal");
    doc.text("This certifies that", width / 2, 75, { align: 'center' });

    doc.setFontSize(30);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(56, 189, 248);
    doc.text(name || "Typing Enthusiast", width / 2, 95, { align: 'center' });

    doc.setFontSize(16);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(255, 255, 255);
    doc.text(`has successfully completed the Singulariti Typing Test`, width / 2, 115, { align: 'center' });
    
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text(`Typing Speed: ${wpm} WPM`, width / 2, 135, { align: 'center' });
    doc.text(`Accuracy: ${accuracy}%`, width / 2, 150, { align: 'center' });

    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(`Date: ${date}`, width / 2, 175, { align: 'center' });
    doc.text(`Generated by singulariti.app`, width / 2, 185, { align: 'center' });

    doc.save('singulariti-typing-certificate.pdf');
  } catch (error) {
    console.error('Error generating certificate:', error);
  }
}
