import React from 'react';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { buildMetadata } from '@/lib/seo/metadata';
import { getPageSEO } from '@/lib/seo/pageMetadata';

const seo = getPageSEO('disclaimer')!;
export const metadata = buildMetadata({
  title: seo.title,
  description: seo.description,
  canonical: `https://singulariti.in${seo.path}`,
  robots: seo.robots,
  openGraph: {
    title: seo.openGraph.title,
    description: seo.openGraph.description,
    url: seo.openGraph.url,
    type: seo.openGraph.type,
    image: seo.openGraph.image,
  },
  twitter: {
    title: seo.twitter.title,
    description: seo.twitter.description,
    image: seo.twitter.image,
  },
});

export default function DisclaimerPage() {
  return (
    <>
      <Header />
      <main className="flex-1 w-full flex flex-col items-center pt-24 pb-12">
        <section className="container mx-auto px-4 max-w-3xl font-sans text-slate">
          <h1 className="font-display font-bold text-4xl text-ink mb-3">Disclaimer</h1>
          <p className="text-sm text-slate mb-8">Last Updated: June 12, 2026</p>

          <p className="mb-6 leading-relaxed">
            The information and tools provided by <strong>Singulariti</strong> ("we," "us," or "our") on <a href="https://singulariti.in" className="text-primary hover:underline">singulariti.in</a> (the "Site") are for general informational and educational purposes only. All information on the Site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or output generated by our tools.
          </p>

          <h2 className="font-display font-bold text-2xl text-ink mt-8 mb-4">1. Professional Advice Disclaimer</h2>
          <p className="mb-4 leading-relaxed">
            The Site cannot and does not contain professional financial, legal, or medical advice. Any financial calculators (e.g., EMI calculators, SIP calculators) or data processing utilities provided on the Site are solely for educational and estimated purposes. 
          </p>
          <p className="mb-6 leading-relaxed">
            The use or reliance of any information contained on the Site or the output from any of our utilities is solely at your own risk. Always consult with a qualified professional before making any financial, legal, or other significant decisions based on calculations or data processed through our tools.
          </p>

          <h2 className="font-display font-bold text-2xl text-ink mt-8 mb-4">2. Tool Accuracy and Reliability</h2>
          <p className="mb-4 leading-relaxed">
            While we strive to ensure that the tools, calculators, and utilities on Singulariti are accurate and up-to-date, software is inherently subject to bugs, limitations, and edge cases. We do not guarantee that the tools will meet your specific requirements, be uninterrupted, entirely secure, or perfectly error-free.
          </p>
          <ul className="list-disc pl-6 mb-6 space-y-2 leading-relaxed">
            <li><strong>Browser Variability:</strong> Because our tools execute locally in your web browser (client-side), performance and outcomes may vary depending on your device's processing power, memory availability, and browser version.</li>
            <li><strong>Data Loss:</strong> We are not responsible for any data loss, file corruption, or system issues that may occur while using our browser-based file conversion, compression, or editing tools. Always maintain backups of your original files.</li>
          </ul>

          <h2 className="font-display font-bold text-2xl text-ink mt-8 mb-4">3. External Links Disclaimer</h2>
          <p className="mb-4 leading-relaxed">
            The Site may contain (or you may be sent through the Site) links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.
          </p>
          <p className="mb-6 leading-relaxed">
            We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the Site.
          </p>

          <h2 className="font-display font-bold text-2xl text-ink mt-8 mb-4">4. "As Is" and "As Available" Basis</h2>
          <p className="mb-6 leading-relaxed">
            All tools and services provided on Singulariti are provided on an "AS IS" and "AS AVAILABLE" basis without any warranties of any kind. To the fullest extent permitted by applicable law, we disclaim all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose.
          </p>

          <h2 className="font-display font-bold text-2xl text-ink mt-8 mb-4">5. Limitation of Liability</h2>
          <p className="mb-6 leading-relaxed">
            In no event shall Singulariti, its developers, partners, or affiliates be liable to you or any third party for any direct, indirect, consequential, exemplary, incidental, special, or punitive damages, including lost profit, lost revenue, loss of data, or other damages arising from your use of the Site or our utilities, even if we have been advised of the possibility of such damages.
          </p>

          <h2 className="font-display font-bold text-2xl text-ink mt-8 mb-4">6. Updates to this Disclaimer</h2>
          <p className="mb-6 leading-relaxed">
            We reserve the right to amend this disclaimer at any time without prior notice. By continuing to use the Site and our tools, you agree to be bound by the most current version of this disclaimer.
          </p>

          <h2 className="font-display font-bold text-2xl text-ink mt-8 mb-4">Contact Us</h2>
          <p className="mb-6 leading-relaxed">
            If you have any questions, concerns, or require further clarification regarding this disclaimer, please contact us at: <a href="mailto:singulariti.contact@gmail.com" className="text-primary hover:underline">singulariti.contact@gmail.com</a>.
          </p>
        </section>
      </main>
      <Footer />
    </>
  );
}
